const messages = {
    auth: {
        LOGIN_SUCCESS: 'LOGIN SUCCESSFUL',
        ERR_INVALID_CREDENTIALS: 'INVALID CREDENTIALS',
        ERR_WRONG_ACCOUNT_OR_PASSWORD: 'WRONG ACCOUNT OR PASSWORD',
        ERR_TOKEN_MISSING: 'ACCESS TOKEN IS REQUIRED',
        ERR_TOKEN_INVALID: 'INVALID OR EXPIRED ACCESS TOKEN',
        ERR_NO_PERMISSION: 'YOU DO NOT HAVE PERMISSION TO ACCESS THIS RESOURCE',
        ERR_WRONG_OTP: 'OTP IS WRONG',
        ERR_OTP_EXPIRED: 'OTP CODE HAS EXPIRED',
        ERR_ENTER_PASSWORD: 'PLEASE ENTER FULL PASSWORD AND CONFIRMPASSWORD',
        ERR_MATCH_PASSWORD: 'CONFIRMATION PASSWORD DOES NOT MATCH',
        ERR_LEAST_PASSWORD: 'PASSWORD MUST BE AT LEAST 6 CHARACTERS',
        UPDATE_PASSWORD_SUCCESS: 'PASSWORD HAS BEEN UPDATED, PLEASE LOGIN AGAIN',
        ERR_EXISTS_EMAIL: 'EMAIL NOT EXISTS',


    },
    user: {
        USER_CREATED_SUCCESSFULLY: 'USER CREATED SUCCESSFULLY',
        USER_UPDATED_SUCCESSFULLY: 'USER UPDATED SUCCESSFULLY',
        USER_DELETED: 'USER DELETED',
        ERR_USER_NOT_EXISTS: 'USER NOT EXISTS',
        GET_INFO: 'GET INFORMATION USER SUCCESSFUL',
    },
    recruitmentNews: {
        
    },
    file: {
        ERR_ONLY_ACCEPT_PDF: 'ONLY ACCEPT FILE PDF',
        ERR_ONLY_ACCEPT_IMAGE: 'ONLY ACCEPT FILE IMAGE',
        ERR_FILE_NOT_EXISTS: 'FILE NOT EXISTS',
        FILE_UPLOAD_ACCESS: 'UPLOAD ACCESS',
    },
    error: {
        ERR_INTERNAL: 'SOMETHING WENT WRONG. PLEASE TRY AGAIN LATER.',
        ERR_DELETE_ADMIN: 'CANNOT DELETE ADMINISTRATOR',
    },
};

export default messages;
